<?php
/**
 * @file Contains the command that makes all the actual comparisons.
 */

namespace surangapg\Heavyd\Command;

use surangapg\Heavyd\HeavydApplication;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

abstract class AbstractHeavydCommandBase extends Command {

  /**
   * @return \surangapg\Heavyd\HeavydApplication
   */
  function getApplication() {
    return parent::getApplication(); // TODO: Change the autogenerated stub
  }
}