<?php

namespace surangapg\Heavyd;

use surangapg\Heavyd\Engine\DockerPhingEngine;
use surangapg\Heavyd\Engine\EngineInterface;
use surangapg\Heavyd\Engine\PhingEngine;
use surangapg\HeavydComponents\Properties\Properties;
use surangapg\HeavydComponents\Properties\PropertiesInterface;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

class HeavydApplication extends Application {

  /**
   * The current version of the application. This will be used to validate
   * or the correct version has been instantiated. Making it easier to keep
   * the workflow application up to date and possibly add an upgrade option
   * later.
   * @const VERSION
   */
  const VERSION = 'alpha';

  /**
   * The engine that does all the heavy lifting.
   *
   * Implemented like this to make it easier to swap to robo or something
   * similar later.
   *
   * @var EngineInterface
   *   The engine to be used to handle the underlying commands.
   */
  protected $engine;

  /**
   * Basepath for the project.
   *
   * @var string
   */
  protected $basePath;

  /**
   * All the properties for the project.
   *
   * @var \surangapg\HeavydComponents\Properties\PropertiesInterface
   *   Properties interface to handle to properties for the project.
   */
  protected $properties;

  /**
   * Creates and returns a fully functional heavyd application based on the current
   * data in a selected heavyd project (this is auto detected).
   *
   * @param string $basePath|null The base directory to start searching for
   *    the .workflow.yml file. Defaults to the current directory. if not set.
   *    This mainly allows for the testing of the application from alternate
   *    base locations.
   *
   * @return HeavydApplication
   *   Fully build application.
   *
   * @throws \Exception
   *
   */
  public static function create($basePath = null) {

    // Use the working directory if none was specified.
    if (!isset($basePath)) {
      $basePath = getcwd();
    }

    // Find the .workflow.yml file and use that as source of the settings
    $projectPath = self::defineBasePath($basePath);

    $properties = Properties::create($basePath);

    $dockerProperties = $properties->get('docker');
    if (isset($dockerProperties['containerActive']) && $dockerProperties['containerActive']) {
      $engine = new DockerPhingEngine($projectPath);
    }
    else {
      $engine = new PhingEngine($projectPath);
    }

    // Fully initialize the application with any extra data from the data file.
    $application = new self($engine, $properties, $projectPath);

    return $application;
  }

  /**
   * HeavydApplication constructor.
   *
   * @param \surangapg\Heavyd\Engine\EngineInterface $engine
   *   Engine to do all the heavy lifting.
   * @param \surangapg\HeavydComponents\Properties\PropertiesInterface $properties
   *   Properties set as loaded from the project.
   * @param string $projectPath
   *   The root location for the project.
   */
  public function __construct(EngineInterface $engine, PropertiesInterface $properties, string $projectPath) {
    parent::__construct('HeavyD', static::VERSION);

    $this->engine = $engine;
    $this->properties = $properties;
    $this->basePath = $projectPath;
  }

  /**
   * @inheritdoc
   */
  public function add(Command $command)
  {
    $command = parent::add($command);

    if (isset($command)) {
      $command->addOption('silent-engine', 'S', InputOption::VALUE_NONE, 'Suppress all the output from the engine.');
    }
  }

  /**
   * Handle a run of a given command.
   *
   * @param InputInterface $input
   *   Input for the command.
   * @param OutputInterface $output
   *   Output generated by the command.
   *
   * @return int
   *   Exit code for the command being run.
   */
  public function doRun(InputInterface $input, OutputInterface $output) {

    /*
     * Display some information about the properties as needed.
     */
    $isInfo = (true === $input->hasParameterOption(array('--info', '-I'), true));
    if ($isInfo || $output->getVerbosity() >= OutputInterface::VERBOSITY_DEBUG) {

      $this->outputCurrentState(new SymfonyStyle($input, $output));

      if ($isInfo) {
        return 0;
      }
    }

    $isSilentEngine = (true === $input->hasParameterOption(array('--silent-engine', '-S'), true));
    $this->getEngine()->setSilent($isSilentEngine);
    $this->getEngine()->setOutput($output);

    parent::doRun($input, $output);
  }

  /**
   * Define the project path for this command.
   * @param string $basePath Basepath to start searching from
   * @return string|null
   * @throws \Exception
   */
  public static function defineBasePath($basePath = null) {
    $basePath = isset($basePath) ? $basePath : getcwd();
    $marker = static::findHeavydMarkerInTree($basePath);
    return dirname($marker);
  }

  /**
   * Rebuild the current properties.
   *
   * Flushes and rebuilds the properties. This will acount for any changes
   * made to the property set during the course of a single command run.
   * For example when a command resets an environment and then needs access to
   * the properties of the new environment.
   */
  function rebuildProperties() {
    $this->setProperties(Properties::create($this->getProperties()->getBasePath()));
  }

  /**
   * Outputs the current state to the cli.
   *
   * @param \Symfony\Component\Console\Style\SymfonyStyle $io
   *   Symfony style to use.
   */
  function outputCurrentState(SymfonyStyle $io) {
    $projectProperties = $this->getProperties()->get('project');

    $io->writeln('<fg=yellow>Current state</>');
    $io->writeln(sprintf(' env: <fg=white>%s</>', $projectProperties['active']['env'] ? $projectProperties['active']['env'] : 'none'));
    $io->writeln(sprintf(' stage: <fg=white>%s</>', $projectProperties['active']['stage'] ? $projectProperties['active']['stage'] : 'none'));
    $io->writeln(sprintf(' site: <fg=white>%s</>', $projectProperties['active']['site'] ? $projectProperties['active']['site'] : 'none'));
    $io->newLine();

    $io->writeln('<fg=yellow>Current Engine</>');
    $io->writeln(sprintf(' engine: <fg=white>%s</>', get_class($this->engine)));
    $io->newLine();
  }

  /**
   * @return \surangapg\Heavyd\Engine\EngineInterface
   */
  public function getEngine() {
    return $this->engine;
  }

  /**
   * @param \surangapg\Heavyd\Engine\EngineInterface $engine
   */
  public function setEngine(EngineInterface $engine) {
    $this->engine = $engine;
  }

  /**
   * @return string
   */
  public function getBasePath() {
    return $this->basePath;
  }

  /**
   * @param $basePath
   */
  public function setBasePath(string $basePath) {
    $this->basePath = $basePath;
  }

  /**
   * @return \surangapg\HeavydComponents\Properties\PropertiesInterface
   */
  public function getProperties() {
    return $this->properties;
  }

  /**
   * @param \surangapg\HeavydComponents\Properties\PropertiesInterface $properties
   */
  public function setProperties(PropertiesInterface $properties) {
    $this->properties = $properties;
  }

  /**
   * Find the heavyD marker recursively in the directory tree.
   *
   * @param string $dir
   *   The directory to search in.
   *
   * @return string
   *   The heavyd file detected.
   *
   * @throws \Exception
   *   If no file could be found in the current tree.
   */
  private static function findHeavydMarkerInTree(string $dir) {
    $path = rtrim($dir, '/') . '/.heavyd.yml';
    if (!file_exists($path)) {

      if ($dir == '/') {
        throw new \Exception("Couldn't locate .heavyd marker in any of the directories. Are you sure heavyd has been properly initialized?");
      }

      return static::findHeavydMarkerInTree(dirname($dir));
    }

    return $path;
  }
}
